spring:
  profiles:
    active: testdata
  application:
    name: catalog-app
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/catalog_db
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  sql:
    init:
      mode: always

catalog:
  greeting: "Welcome to the local book catalog"